input {
  tcp {
    port => 5000
    codec => json_lines
  }

  file {
    path => ["/logs/*.log"]
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {

  # 🔥 DO NOT DROP LOCAL IPs (important for portal)
  # if [source_ip] =~ /^(127\.|10\.|192\.168\.|172\.)/ {
  #   drop { }
  # }

  # Deduplication
  fingerprint {
    source => ["event_id"]
    target => "doc_id"
    method => "SHA1"
  }

  # GeoIP enrichment
  geoip {
    source => "source_ip"
    target => "geoip"
  }

  # Fix geo field for Kibana
  mutate {
    rename => { "[geoip][geo][location]" => "[geoip][location]" }
  }

  # Clean fields
  mutate {
    remove_field => ["message", "event.original"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "honeypot-logs"
    document_id => "%{doc_id}"
  }

  stdout { codec => rubydebug }
}