input {
  file {
    path => ["/logs/banking.log", "/logs/api.log", "/logs/ssh.log"]
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  mutate {
    add_field => {
      "project" => "PRJN26-213"
      "environment" => "honeypot-finance"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "finance-honeypot-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}